n = input('digite algo ')
print('Esse valor é? ', (type)(n))
print('Ele é númerico? ', n.isnumeric())
print('Ele é alfabeto? ', n.isalpha())
print('Ele está em maiusculo? ', n.isupper())
print('Ele está em minusculo? ', n.islower())
print('Ele é um digito? ', n.isdigit())
print('Ele é um decimal? ', n.isdecimal())
print('Tchau dxzin fofolol')
 
